### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dazhbog** [energia/EasyLink#1]
Hello,

How can i run this? Is there a link to some documentation? Is it a standard energia library process? i guess it needs arm-eabi stuff..

Thanks!

**Comment by robertinant** [comment]
This is an Energia library to be used with the Energia IDE and the cc13xx core. I have just released with core and the library through the board and library manager in the Energia IDE. The documentation is in progress and can be found here: http://energia.nu/reference/easylink/
