### ISSUE TITLE
Cc1310 library in embedded c

### ISSUE THREAD

**Issue by github4f** [energia/EasyLink#5]
Hi-First of all thanks for providing the Easylink library. Since I am not very familiar with Energia, I have a basic question. I would like to use the library in my embedded c code (instead of Energia). I was wondering it is possible? Or I need to stick to Energia for using the library? Thanks

**Comment by robertinant** [comment]
The EasyLink C++ library is a wrapper for the CC1310 easylink software. Please see the details here: http://www.ti.com/tool/cc13xx-sw
