### ISSUE TITLE
IoT gateway

### ISSUE THREAD

**Issue by github4f** [energia/EasyLink#6]
Hi, I was wondering is it possible to use energia with TM4C129 and CC1310 to build an IoT gateway. 
I see a soluitio in TI (http://www.ti.com/tool/TIDM-TM4C129XGATEWAY#1) including the firmware. Bit I cannot figure our how it is possible to use Easylink in TM4C129 to use CC1310 as a kind of network processor? Tnx

**Comment by robertinant** [comment]
This is possible and as far as I can see you should be able to reuse some of the code from the reference design. You would have to hookup the CC1310 to the TM4C129 via uart and use the command set interface from the reference design. Both the code for the CC1310 and the TM4C129 can be written in Energia.

With that said, you would be better off using a CC1310 LaunchPad + CC3100 WiFi BoosterPack as the gateway.

**Comment by robertinant** [comment]
I would also recommend to post this question in the Energia forum here: http://forum.43oh.com/forum/125-energia-tivaccc3xxx/.
